def raise_exception_msg():
    raise NameError("This is a custom name exception")